image: python:3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
    - git config user.name ${GITLAB_USER_NAME}
    - git config user.email sascha.markus@gmail.com
    # Using chrom headless integration from https://github.com/joyzoursky/docker-python-chromedriver
    # install google chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - apt-get -y update
    - apt-get install -y google-chrome-stable

    # install chromedriver
    - apt-get install -yqq unzip
    - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
    - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

    # set display port to avoid crash
    - export DISPLAY=:99
    # generate page
    - pip install -r requirements.txt
    - python selenium_flaneur.py
    
    # add the generated content to flanuer_content repo
    # - git add content/ && git commit -m "new post [skip ci]"   || true
    # - git push "https://saschamarkus:${GITLAB_KEY}@${CI_REPOSITORY_URL#*@}" "HEAD:master"  || true
  script:
    - apt-get -qq update
    - pelican -s publishconf.py
    # copy certificate
    - mkdir public/.well-known
    - mkdir public/.well-known/acme-challenge
    - cp -r .well-known/acme-challenge/* public/.well-known/acme-challenge/
  artifacts:
    paths:
      - public/

